# Generated by Django 3.2.4 on 2021-11-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_diary_diary_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kakaotoken',
            field=models.TextField(max_length=200),
        ),
    ]
