# Generated by Django 3.2.4 on 2021-11-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_user_kakaotoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_img',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
