# Generated by Django 3.2.4 on 2021-11-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_diary_diary_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diary',
            name='diary_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diary',
            name='diary_todayme',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='diary_tomorrowme',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='diary_weather',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='kakaotoken',
            field=models.TextField(),
        ),
    ]
